### ISSUE TITLE
cannot install package via Xcode

### ISSUE THREAD

**Issue by twop** [ValentinWalter/Honey#2]
here is the log
> Dependencies could not be resolved because 'Honey' >= 1.0.1 depends on 'Middleman' 1.0.0..<2.0.0 and root depends on 'Honey' 1.0.1..<2.0.0.
'Middleman' >= 1.0.0 cannot be used because package 'middleman' is required using a stable-version but 'middleman' depends on an unstable-version package 'stringcase' and no versions of 'Middleman' match the requirement 1.0.1..<2.0.0.

Wanted to test your package but got stuck here. Sorry if there is an easy workaround that I'm not aware of. I'm not a swift developer

**Comment by ValentinWalter** [comment]
Thanks for reporting this! Let me know if it works now.

**Comment by twop** [comment]
It works now! Tnx!
